metadata.format.version = "1.1"

[versions]

# Server Software
spigot = "1.16.5-R0.1-SNAPSHOT"

# ServerAssistantAI itself
serverassistantai = "1.4-SNAPSHOT"

# Dependencies
langchain4j = "1.2.0-beta8"
langchain4j-stable = "1.2.0"
retrofit2 = "3.0.0"

# Annotations
lombok = "1.18.38"

[libraries]

# Server Software
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }

# ServerAssistantAI itself
serverassistantai = { group = "dev.bluetree242.serverassistantai", name = "api", version.ref = "serverassistantai" }

# Dependencies
langchain4j-anthropic = { group = "dev.langchain4j", name = "langchain4j-anthropic", version.ref = "langchain4j-stable" }
langchain4j-azureopenai = { group = "dev.langchain4j", name = "langchain4j-azure-open-ai", version.ref = "langchain4j-stable" }
langchain4j-mistralai = { group = "dev.langchain4j", name = "langchain4j-mistral-ai", version.ref = "langchain4j-stable" }
langchain4j-googleai = { group = "dev.langchain4j", name = "langchain4j-google-ai-gemini", version.ref = "langchain4j-stable" }
langchain4j-huggingface = { group = "dev.langchain4j", name = "langchain4j-hugging-face", version.ref = "langchain4j" }

retrofit2-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }

# Annotations
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }